---
homebrew_installed_packages:
  - ack
  - angular-cli
  - ansiweather
  - asciidoctor
  - awk
  - awscli
  - azure-cli
  - ballerina
  - chrome-cli
  - coreutils
  - diffutils
  - docker
  - docker-completion
  - duck
  - emojify
  - exercism
  - findutils
  - gcutil
  - git
  - git-cal
  - git-lfs
  - git-quick-stats
  - graphviz
  - grep
  - gzip
  - helm
  - hugo
  - ipython
  - jupyterlab
  - kubeless
  - kubernetes-cli
  - mas
  - netcat6
  - nmap
  - node
  - opencv
  - openssl@1.1
  - packer
  - plantuml
  - pulumi
  - tcpdump
  - terraform
  - terraform-docs
  - typescript
  - watch
  - wget
  - whois
  - wireshark
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-git-prompt
  - zsh-history-substring-search
  - zzz

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-eid
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - brave-browser
  - cyberduck
  - dash
  - docker
  - firefox
  - font-powerline-symbols
  - font-roboto-mono-for-powerline
  - fork
  - gimp
  - google-chrome
  - google-cloud-sdk
  - googleappengine
  - inkscape
  - insomnia
  - iterm2
  - logitech-presentation
  - multipass
  - pgadmin4
  - postgres
  - postman
  - signal
  - tresorit
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - zoomus

mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine"}
  - { id: 641027709, name: "Color Picker"}
  - { id: 682658836, name: "GarageBand" }
  - { id: 1474276998, name: "HP Smart" }
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 441258766, name: "Magnet" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1346203938, name: "OmniFocus" }
  - { id: 409201541, name: "Pages" }
  - { id: 803453959, name: "Slack" }
  - { id: 497799835, name: "XCode" }

mas_upgrade_all_apps: no
mas_signin_dialog: no

dockutil_url: https://raw.githubusercontent.com/kcrawford/dockutil/master/scripts/dockutil
dockutil_install_path: /usr/local/bin/dockutil

dockitems_remove_all: false

dockitems_disabled:
  - Mail
  - Safari
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - App Store
  - System Preferences
  - Calendar
  - Terminal

dockitems_enabled:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Spark
    path: "/Applications/Spark.app"
    pos: 2
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 5

dotfiles_repo: "https://github.com/blackbee-ai/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_local_destination: "~/Projects/personal/dotfiles"
dotfiles_repo_accept_hostkey: true
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zshrc.local
