---
homebrew_installed_packages:
  - asciidoctor
  - awscli
  - cfssl
  - curl
  - dep
  - direnv
  - elixir
  - elm
  - elm-format
  - erlang
  - fzf
  - git
  - git-lfs
  - gnu-tar
  - go
  - graphviz
  - gzip
  - hugo
  - jq
  - node
  - packer
  - pre-commit
  - pstree
  - terraform
  - terraform-docs
  - watch
  - wget
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-eid
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - azure-data-studio
  - balenaetcher
  - brave-browser
  - dash
  - discord
  - dropbox
  - duet
  - eid-be
  - eid-be-viewer
  - firefox
  - focus
  - font-powerline-symbols
  - font-roboto-mono-for-powerline
  - gitter
  - insomnia
  - istat-menus
  - iterm2
  - keybase
  - little-snitch
  - micro-snitch
  - multifirefox
  - omnifocus
  - spectrum
  - slack
  - sourcetree
  - spotify
  - telegram
  - trainerroad
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - viscosity
  - visual-studio-code
  - vlc
  - whatsapp
  - wifi-explorer
  - zoho-docs
  - zoho-workdrive
  - zoomus

mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 824171161, name: "Affinity Designer" }
  - { id: 918858936, name: "Airmail 3" }
  - { id: 1205882554, name: "Cliq - Team communication" }
  #  - { id: 1350225911, name: "Create Booklet 2" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 406056744, name: "Evernote" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 441258766, name: "Magnet" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 403504866, name: "PCalc" }
  - { id: 407963104, name: "Pixelmator" }
  - { id: 1384080005, name: "Tweetbot 3 for Twitter" }
  - { id: 810962929, name: "Writer - Online Word Processor" }
  - { id: 497799835, name: "XCode" }
mas_upgrade_all_apps: no
mas_signin_dialog: no

dockutil_url: https://raw.githubusercontent.com/kcrawford/dockutil/master/scripts/dockutil
dockutil_install_path: /usr/local/bin/dockutil

dockitems_remove_all: false

dockitems_disabled:
  - Mail
  - Safari
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - App Store
  - System Preferences
  - Calendar
  - Terminal

dockitems_enabled:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Airmail 3
    path: "/Applications/Airmail 3.app"
    pos: 2
  - name: Calendar
    path: "/Applications/Calendar.app"
    pos: 3
  - name: MultiFirefox
    path: "/Applications/MultiFirefox.app"
    pos: 4
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 5
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 6
