---
homebrew_installed_packages:
  - asciidoctor
  - awscli
  - cfssl
  - curl
  - dep
  - direnv
  - elixir
  - elm
  - elm-format
  - erlang
  - git
  - git-lfs
  - go
  - graphviz
  - gzip
  - hugo
  - jq
  - packer
  - pre-commit
  - pstree
  - terraform
  - watch
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - dash
  - dropbox
  - firefox
  - slack
  - vagrant

