---

- hosts: localhost
  connection: local

  tasks:
    - name: homebrew taps
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/cask-eid
        - homebrew/cask-fonts
