name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install Ansible
        run: |
          sudo easy_install pip
          sudo pip install ansible
          "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
          sudo mkdir -p /etc/ansible
          sudo touch /etc/ansible/hosts
          "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

      - name: Run Ansible
        run: |
          ansible-galaxy install -r requirements.yml
          ansible-playbook ringods.yml --syntax-check
          ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' --skip-tags appstore ringods.yml

      - name: Check idempotence
        run: |
          idempotence=$(mktemp)
          ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' --skip-tags appstore ringods.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
